Repository torchbox/wagtailmedia, pull requests merged in 2019-05, with the labels that each got.

#55 Add issue template from Wagtail
  .github/ISSUE_TEMPLATE.md
Labels: enhancement

#40 upgrade edit_handlers API to 2.0
  CHANGELOG.md
  wagtailmedia/edit_handlers.py
Labels: enhancement

#56 Add EditorConfig
  .editorconfig
Labels: enhancement

#57 Document media field name clash. Fix #54
  README.md
Labels: documentation

#58 Release v0.3.1
  CHANGELOG.md
  wagtailmedia/__init__.py
Labels: bug
