Repository torchbox/wagtailmedia, pull requests merged in 2020-11, with the labels that each got.

#107 Exclude tests folder from published package
  MANIFEST.in
Labels: bug

#116 Update supported & tested Python, Django, Wagtail versions
  .travis.yml
  setup.py
  tox.ini
  vagrant/README
  vagrant/provision.sh
Labels: enhancement

#119 Switch to GitHub actions, pre-commit support, black
  .github/workflows/pre-commit.yml
  .github/workflows/test.yml
  .pre-commit-config.yaml
  .travis.yml
  README.md
  SPECIFICATION.md
  manage.py
  runtests.py
  setup.cfg
  setup.py
  vagrant/Vagrantfile
  wagtailmedia/__init__.py
  wagtailmedia/admin.py
  wagtailmedia/admin_urls.py
  wagtailmedia/apps.py
  wagtailmedia/blocks.py
  wagtailmedia/edit_handlers.py
  wagtailmedia/forms.py
  wagtailmedia/migrations/0001_initial.py
  wagtailmedia/migrations/0002_initial_data.py
  wagtailmedia/migrations/0003_copy_media_permissions_to_collections.py
  wagtailmedia/migrations/0004_duration_optional_floatfield.py
  wagtailmedia/models.py
  wagtailmedia/permissions.py
  wagtailmedia/templates/wagtailmedia/media/_file_field_as_li.html
  wagtailmedia/templates/wagtailmedia/media/_thumbnail_field_as_li.html
  wagtailmedia/templates/wagtailmedia/media/edit.html
  wagtailmedia/templates/wagtailmedia/media/list.html
  wagtailmedia/templates/wagtailmedia/media/results.html
  wagtailmedia/tests/.gitignore
  wagtailmedia/tests/settings.py
  wagtailmedia/tests/test_blocks.py
  wagtailmedia/tests/test_form_override.py
  wagtailmedia/tests/test_models.py
  wagtailmedia/tests/test_permissions.py
  wagtailmedia/tests/test_views.py
  wagtailmedia/tests/testapp/__init__.py
  wagtailmedia/tests/testapp/apps.py
  wagtailmedia/tests/testapp/fixtures/test.json
  wagtailmedia/tests/testapp/forms.py
  wagtailmedia/tests/testapp/migrations/0001_initial.py
  wagtailmedia/tests/testapp/models.py
  wagtailmedia/tests/urls.py
  wagtailmedia/utils.py
  wagtailmedia/views/chooser.py
  wagtailmedia/views/media.py
  wagtailmedia/wagtail_hooks.py
  wagtailmedia/widgets.py
Labels: Type: Cleanup

#121 Only show MediaSummaryItem for users that can add/manage Media
  wagtailmedia/wagtail_hooks.py
Labels: Type: Cleanup

#120 Remove deprecated BaseMediaChooserPanel
  wagtailmedia/edit_handlers.py
Labels: Type: Cleanup
